--TABLAS
CREATE TABLE ESPECIFICACIONESDEPRODUCTOS
(
PRODESPEID NUMBER(10) NOT NULL,
TALLA VARCHAR2(5),
COLOR VARCHAR2(10),
LARGO NUMBER(10,2),
ANCHO NUMBER(10,2),
ALTO NUMBER(10,2),
PESO NUMBER(10,2),
PRODUCTOID NUMBER(10) NOT NULL
);

CREATE TABLE MODELOSDEPRODUCTOS
(
MODELOID NUMBER(10) NOT NULL,
FECHA DATE NOT NULL
);

CREATE TABLE MARCASDEPRODUCTOS
(
MARCAID NUMBER(10) NOT NULL,
NOMBRE VARCHAR2(20) NOT NULL
);

CREATE TABLE CATEGORIASDEPRODUCTOS
(
CATEGORIAID NUMBER(10) NOT NULL,
NOMBRE VARCHAR2(20) NOT NULL
);

CREATE TABLE PRODUCTOS
(
PRODUCTOID NUMBER(10) NOT NULL,
NOMBRE VARCHAR2(10) NOT NULL,
MARCAID NUMBER(10) NOT NULL,
MODELOID NUMBER(10) NOT NULL,
CATEGORIAID NUMBER(10) NOT NULL
);

CREATE TABLE CONTIENEN
(
ESPEPRODUCTOS NUMBER(10) NOT NULL,
VENTAS NUMBER(10) NOT NULL,
CANTIDAD NUMBER(10) NOT NULL,
PRECIO NUMBER(10,2) NOT NULL
);

CREATE TABLE VENTAS     
(
VENTAID NUMBER(10) NOT NULL,
VALORTOTAL NUMBER(10) NOT NULL,
FECHAHORA DATE NOT NULL,
DESCUENTO NUMBER(10,2),
CLIENTE NUMBER(10) NOT NULL
);

CREATE TABLE ENLINEA
(
VENTAID NUMBER(10) NOT NULL,
DIRECCION NUMBER(10) NOT NULL,
TC NUMBER(12) NOT NULL,
CVV NUMBER(4) NOT NULL,
FECHADEVENCIMIENTOTC DATE NOT NULL
);

CREATE TABLE CLIENTES
(
CLIENTEID NUMBER(10) NOT NULL,
DIRECCION NUMBER(10)
);

CREATE TABLE PERSONAS(
CLIENTEID NUMBER(10) NOT NULL,
NOMBRE VARCHAR2(40) NOT NULL
);

CREATE TABLE EMPRESAS(
CLIENTEID NUMBER(10) NOT NULL,
NOMBREEMPRESA VARCHAR2(50) NOT NULL
);

CREATE TABLE DIRECCIONES
(
DIRECCIONID NUMBER(10) NOT NULL,
CIUDAD VARCHAR2(20)NOT NULL,
DIRECCION VARCHAR2(50) NOT NULL
);

CREATE TABLE BODEGAS
(
ESTID NUMBER(10) NOT NULL,
DIRECCION VARCHAR2(30) NOT NULL,
CIUDAD VARCHAR2(20) NOT NULL
);

CREATE TABLE EXISTENCIAS
(
ESPEPRODUCTOS NUMBER(10) NOT NULL,
DIRECCIONES NUMBER(10) NOT NULL,
CANTIDAD NUMBER(10) NOT NULL
);
