--PRIMARIAS
ALTER TABLE ESPECIFICACIONESDEPRODUCTOS ADD CONSTRAINT PK_ESPPROD PRIMARY KEY (PRODESPEID);
ALTER TABLE MARCASDEPRODUCTOS ADD CONSTRAINT PK_MARCASDEPRODUCTOS PRIMARY KEY (MARCAID);
ALTER TABLE CATEGORIASDEPRODUCTOS ADD CONSTRAINT PK_CATEGORIASDEPRODUCTOS PRIMARY KEY (CATEGORIAID);
ALTER TABLE MODELOSDEPRODUCTOS ADD CONSTRAINT PK_MDEPRODUCTOS PRIMARY KEY (MODELOID);

ALTER TABLE PRODUCTOS ADD CONSTRAINT PK_PRODUCTOS PRIMARY KEY (PRODUCTOID);

ALTER TABLE CONTIENEN ADD CONSTRAINT PK_contienen PRIMARY KEY (ESPEPRODUCTOS,VENTAS);

ALTER TABLE VENTAS ADD CONSTRAINT PK_VENTAS PRIMARY KEY (VENTAID);
ALTER TABLE ENLINEA ADD CONSTRAINT PK_ENLINEA PRIMARY KEY (VENTAID);

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (CLIENTEID); 

ALTER TABLE PERSONAS ADD CONSTRAINT PK_PERSONAS PRIMARY KEY (CLIENTEID); 

ALTER TABLE EMPRESAS ADD CONSTRAINT PK_EMPRESASS PRIMARY KEY (CLIENTEID); 

ALTER TABLE DIRECCIONES ADD CONSTRAINT PK_DIRECCIONES PRIMARY KEY (DIRECCIONID);

ALTER TABLE BODEGAS ADD CONSTRAINT PK_BODEGAS PRIMARY KEY (ESTID);
ALTER TABLE EXISTENCIAS ADD CONSTRAINT PK_CANTIDADES PRIMARY KEY (ESPEPRODUCTOS,DIRECCIONES);
--?????????

--UNICAS
ALTER TABLE EMPRESAS ADD CONSTRAINT UK_EMPRESAS_NOMEMPRESA UNIQUE(NOMBREEMPRESA);


--FORANEAS FALTAN
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_DIR FOREIGN KEY (DIRECCION) REFERENCES DIRECCIONES(DIRECCIONID);
ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_CLIENTES FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(CLIENTEID);
--error 
--la taba no existe--ALTER TABLE PRODUCTOSVENDIDOS ADD CONSTRAINT FK_PROVEN_VENTAS FOREIGN KEY (VENTA) REFERENCES VENTAS(VENTAID);
--la taba no existe--ALTER TABLE PRODUCTOSVENDIDOS ADD CONSTRAINT FK_PROVEN_ESPROD FOREIGN KEY (ESPECIFICACIONDEPRODUCTO) REFERENCES ESPECIFICACIONESDEPRODUCTOS(PRODESPEID);
--la taba no existe--ALTER TABLE CANTIDADES ADD CONSTRAINT FK_CANTIDADES_ESPROD FOREIGN KEY (ESPECIFICACIONDEPRODUCTO) REFERENCES ESPECIFICACIONESDEPRODUCTOS(PRODESPEID);
--la taba no existe--ALTER TABLE CANTIDADES ADD CONSTRAINT FK_CANTIDADES_BODEGAS FOREIGN KEY (BODEGA) REFERENCES BODEGAS(ESTID);
--error 



ALTER TABLE ENLINEA ADD CONSTRAINT FK_ENLINEA_VENTAS FOREIGN KEY (VENTAID) REFERENCES VENTAS(VENTAID);
ALTER TABLE ENLINEA ADD CONSTRAINT FK_ENLINEA_DIRECCIONES FOREIGN KEY (DIRECCION) REFERENCES DIRECCIONES(DIRECCIONID);
ALTER TABLE PERSONAS ADD CONSTRAINT FK_PERSONAS_CLIENTES FOREIGN  KEY (CLIENTEID) REFERENCES CLIENTES (CLIENTEID);
ALTER TABLE EMPRESAS ADD CONSTRAINT FK_EMPRESAS_CLIENTES FOREIGN  KEY (CLIENTEID) REFERENCES CLIENTES (CLIENTEID);
ALTER TABLE ESPECIFICACIONESDEPRODUCTOS ADD CONSTRAINT FK_ESPRODUCT_PRODUCTOS FOREIGN  KEY (PRODUCTOID) REFERENCES PRODUCTOS (PRODUCTOID);
ALTER TABLE PRODUCTOS  ADD CONSTRAINT FK_PRODUCTOS_MARCA FOREIGN  KEY (MARCAID) REFERENCES MARCASDEPRODUCTOS(MARCAID);
ALTER TABLE PRODUCTOS  ADD CONSTRAINT FK_PRODUCTOS_MODELO FOREIGN  KEY (MODELOID) REFERENCES MODELOSDEPRODUCTOS(MODELOID);
ALTER TABLE PRODUCTOS  ADD CONSTRAINT FK_PRODUCTOS_CATEGORIA FOREIGN  KEY (CATEGORIAID) REFERENCES CATEGORIASDEPRODUCTOS(CATEGORIAID);
--HOY
ALTER TABLE CONTIENEN ADD CONSTRAINT FK_CONTIENEN_VENTAS FOREIGN KEY (VENTAS) REFERENCES VENTAS(VENTAID);
ALTER TABLE CONTIENEN ADD CONSTRAINT FK_CONTIENEN_ESPPRO FOREIGN KEY (ESPEPRODUCTOS) REFERENCES ESPECIFICACIONESDEPRODUCTOS(PRODESPEID);
ALTER TABLE EXISTENCIAS ADD CONSTRAINT FK_EXISTENCIAS_ESPPRO FOREIGN KEY (ESPEPRODUCTOS) REFERENCES ESPECIFICACIONESDEPRODUCTOS(PRODESPEID);
ALTER TABLE EXISTENCIAS ADD CONSTRAINT FK_EXISTENCIAS_BODEGAS FOREIGN KEY (DIRECCIONES) REFERENCES BODEGAS(ESTID);